### ISSUE TITLE
Close panes with ended session

### ISSUE THREAD

**Issue by alphahot1** [ilikejam/csshi#3]
Hi and thanks for the script. Is it possible to autclose inactive session? For ex. I use it like this:
`csshi myserver{01..99}.mydomain` and it spins out several panes, but a lot of them are unreachable/nonexistent servers. 
It would be nice if it could autoclose the inactive panes. I tried to set  ` profile.set_close_sessions_on_end(False)` to false in gen_ssh_profile() but it messed up something and it didn't work as espected.

Thanks!

**Comment by ilikejam** [comment]
Hi!

That sounds reasonable.

The only issue is that it's not (as far as I'm aware) possible to re-balance panes across different columns, so if you get a lot of closed sessions in one column you'll end up with very different sized panes.

Try the script in https://github.com/ilikejam/csshi/tree/3-close-panes-with-ended-session , see if it does what you expect.

**Comment by ilikejam** [comment]
'-k' flag for autoclose.

**Comment by alphahot1** [comment]
Thanks for the fast response! Unfortunately with or without -k it doesn't seem to make any difference for me. I've ended up with a bunch of panes with  "===Session Ended===" on them.

**Comment by ilikejam** [comment]
That's odd. Can you run it with '-d' and add the debug output from the csshi command here? (Remove anything that's secret!)

**Comment by ilikejam** [comment]
Could be that the sessions are ending before the panes are set to auto-close. Might have to rethink the strategy.

**Comment by alphahot1** [comment]
Sure!

```csshi.branch -k -d myhost{91..95}.mydomain
DEBUG: SSH command for host myhost91.mydomain is: ssh myhost91.mydomain
DEBUG: SSH command for host myhost92.mydomain is: ssh myhost92.mydomain
DEBUG: SSH command for host myhost93.mydomain is: ssh myhost93.mydomain
DEBUG: SSH command for host myhost94.mydomain is: ssh myhost94.mydomain
DEBUG: SSH command for host myhost95.mydomain is: ssh myhost95.mydomain
DEBUG: Using shell /usr/local/bin/bash
DEBUG: Entering main()
DEBUG: Launching iTerm...
DEBUG: iTerm launched
DEBUG: Command string is /usr/local/bin/bash -l -c '{ssh_string}'
DEBUG: Connecting to iTerm
DEBUG: Connected
DEBUG: Launching 1st pane
DEBUG: Splitting pane for ssh
DEBUG: Splitting pane for ssh
DEBUG: Splitting pane for ssh
DEBUG: Splitting pane for ssh
DEBUG: Enabling input broadcast
DEBUG: Arranging panes
DEBUG: Activating 1st pane
DEBUG: Setting close_sessions_on_end to True
DEBUG: Main has completed. Exiting.```

Since I have only 3 active hosts there, there result is a window with 2 columns.
- 1st column: host1 (active), host3(active), host5(inactive, ===session ended ===)
- 2nd column: host2 (active), host3(inactive, ===session ended ===)

**Comment by alphahot1** [comment]
It works like a champ!! Thanks for your effort, it wasn't that easy. 
What about this?
>that it's not (as far as I'm aware) possible to re-balance panes across different columns
I ended up with 9 active servers splitted in 4 coluimns (1 pane, 3 panes, 2 panes, 2 panes each). Maybe is it possible to wait for the ssh connection to be estabilished before creating the next split?
Anyway I'm amazed that you implemented that feature and it's good enough as it is!

**Comment by ilikejam** [comment]
It all feels a bit of a hack, splitting panes to make new sessions, but that's what we've got to play with. Once the panes are split, there isn't much manipulation you can do. There's a 7 year old bug open to add this functionality to the APIs, so I don't think anything's going to change any time soon.

Glad it's working for you though!

I'll do some cleanup (that main function's getting a bit long) and merge the changes when I get a minute. I'll ponder some more though - maybe there is a better way...

**Comment by alphahot1** [comment]
Thanks a lot for your effort! I'm going to comment on that bug for sure.
