### ISSUE TITLE
Custom ssh command

### ISSUE THREAD

**Issue by lderugeriis** [ilikejam/csshi#7]
Hi! 
I'd like to be possible to specify a custom ssh command or (maybe better) respect shell aliases.
I have an alias for ssh to sshrc (a script useful to bring shell custom settings to remote servers without touching root bash profiles).  But as I can see csshi just run ssh command + arguments without using the aliased command. For the moment I've just modified to ssh_string variable to use sshrc but it would be nice to have the option.

Thanks,
Luca

**Comment by ilikejam** [comment]
Hi Luca!

Shell aliases aren't going to work unfortunately - they're only available in interactive shells.
I've added a '-b' option so you can specify the binary to be whatever you like (defaults to 'ssh'). Give it a try, it's on the main branch now.

**Comment by lderugeriis** [comment]
Hi! It works wonders. Thanks a lot!

**Comment by ilikejam** [comment]
Awesome!
