### ISSUE TITLE
Read hostnames from file

### ISSUE THREAD

**Issue by lightener** [ilikejam/csshi#8]
This tool would be perfect if it could read hostnames from a file, in addition to taking a list at the command line. 

Something like a `-file` or `-hosts` argument.

**Comment by ilikejam** [comment]
Hi

Had thought about adding a host file option, but it's just extra code when xargs is always available on MacOS:
$ xargs csshi < hosts.txt

**Comment by ilikejam** [comment]
Or do you have a use case that makes xargs unusable?
